### ISSUE TITLE
Natively support Windows on ARM

### ISSUE THREAD

**Issue by azrielgold** [sla80/SmartSvgViewer#5]
I recently discovered your great and simple app. I have a Windows on ARM device and while your app works there, it requires Windows to fire up the virtualization layer (which consumes more power and slows down the machine).
Is there any chance of you compiling a native ARM version of your app?

Thanks a lot!

**Comment by sla80** [comment]
Hello @azrielgold,
There is a special version for you that has not been released yet (ver 0.5.0.1545). Try it, and please tell me whether it works natively on ARM64 or not. Here it is:

[SmartSvgViewerSetup_x64_0.5.0.1545.zip](https://github.com/sla80/SmartSvgViewer/files/13936119/SmartSvgViewerSetup_x64_0.5.0.1545.zip)

**Comment by azrielgold** [comment]
Thanks for the build!
However, it seems to still be running using the x64 emulator as before.
![image](https://github.com/sla80/SmartSvgViewer/assets/51451551/afe23409-45c4-4d5c-ad0c-1f1799ea5926)

**Comment by sla80** [comment]
@azrielgold,

Understood. It was compiled for "Any CPU".
OK, now try this, compiled for ARM64:

[SmartSvgViewerSetup_0.5.0.1550_ARM64.msi.zip](https://github.com/sla80/SmartSvgViewer/files/13946200/SmartSvgViewerSetup_0.5.0.1550_ARM64.msi.zip)

**Comment by azrielgold** [comment]
This ARM64-only build seems to do the trick. Thanks!
![image](https://github.com/sla80/SmartSvgViewer/assets/51451551/14969645-4907-4c0b-a7b9-c077d993cc0d)

**Comment by sla80** [comment]
@azrielgold 

Due to the fact that your special version of the app was a little unfinished, through auto-update, you will receive version 0.5.0.1645 which is built for x64. Then just install the [ARM64 version](https://github.com/sla80/SmartSvgViewer/releases/download/v0.5.0.1645/SmartSvgViewerSetup_ARM64.msi) and you're done. All future updates you will receive will be built for ARM64.

**Comment by azrielgold** [comment]
Great. Thanks for all the help!
